stages:
  - build
  - deploy

# Install dependencies and build the frontend (this can be adapted based on your project)
build:
  stage: build
  image: node:18 # or any other base image suitable for your project
  script:
    - npm install
    - npm run build  # Adjust according to your build command (e.g., `vite build` for Vite projects)
  artifacts:
    paths:
      - dist # or the folder where your built static assets are located

# Deploy to Cloudflare Pages
deploy:
  stage: deploy
  image: curlimages/curl:8.6.0
  script:
    - |
      curl -X POST "https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/deployments" \
      -H "Authorization: Bearer ${CF_API_TOKEN}" \
      -H "Content-Type: application/json" \
      -d '{
        "deployment": {
          "branch": "main", 
          "commit_sha": "${CI_COMMIT_SHA}"
        }
      }'
  only:
    - main  # Ensure deployment happens only when changes are pushed to the 'main' branch
